# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-19 01:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gluttonyTw', '0003_auto_20161124_1926'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feeling', models.CharField(max_length=200, null=True)),
                ('like', models.PositiveSmallIntegerField(default=1)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gluttonyTw.EatUser')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gluttonyTw.ResProf')),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='period',
            field=models.CharField(max_length=1),
        ),
    ]
