# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-19 01:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gluttonyTw', '0004_auto_20170219_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='favordish',
            name='freq',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='favortype',
            name='freq',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='resfavordish',
            name='freq',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='resprof',
            name='ResLike',
            field=models.PositiveSmallIntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='resprof',
            name='score',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='smallorder',
            name='amount',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='userorder',
            name='total',
            field=models.PositiveIntegerField(),
        ),
    ]
