# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-22 07:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DayOfWeek', models.CharField(max_length=1)),
                ('Start', models.CharField(max_length=8)),
                ('CloseMid', models.CharField(max_length=8, null=True)),
                ('StartMid', models.CharField(max_length=8, null=True)),
                ('Close', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DishName', models.CharField(max_length=20, null=True)),
                ('price', models.DecimalField(decimal_places=0, max_digits=6)),
                ('isSpicy', models.BooleanField()),
                ('image', models.ImageField(default='images/time2eat/turkey.svg', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='EatUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FDish', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='t2e.Dish')),
            ],
        ),
        migrations.CreateModel(
            name='FavorDish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('freq', models.DecimalField(decimal_places=0, max_digits=4)),
                ('EatUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='t2e.EatUser')),
                ('dish', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='t2e.Dish')),
            ],
        ),
        migrations.CreateModel(
            name='FavorType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('freq', models.DecimalField(decimal_places=0, max_digits=4)),
                ('EatUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='t2e.EatUser')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='images/time2eat/menu.svg', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateTimeField()),
                ('period', models.CharField(max_length=3)),
                ('total', models.DecimalField(decimal_places=0, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneNum', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='ResFavorDish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('freq', models.DecimalField(decimal_places=0, max_digits=6)),
                ('dateOfMon_Year', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ResProf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ResName', models.CharField(max_length=30, null=True)),
                ('address', models.CharField(max_length=30, null=True)),
                ('ResLike', models.DecimalField(decimal_places=0, default=50, max_digits=6)),
                ('score', models.DecimalField(decimal_places=0, default=3, max_digits=1)),
                ('last_reserv', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=10)),
                ('avatar', models.ImageField(default='images/time2eat/restaurant.svg', upload_to='')),
                ('environment', models.ImageField(default='images/time2eat/burger.svg', upload_to='')),
                ('envText', models.CharField(default='以新鮮食材佐特製湯頭，搭配風格設計空間，讓聚餐除了享受美食，也能提升時尚品味！', max_length=255)),
                ('feature', models.ImageField(default='images/time2eat/noodles.svg', upload_to='')),
                ('featureText', models.CharField(default='均勻分布的油花與鮮紅肉質，讓口感更加紮實不凡，肉獨有的香氣與油花潤飾，放進精心熬煮清甜的湯汁中輕涮，令人流連忘返的香滑柔嫩口感，讓你感動不已！', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SmallOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ResType', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=0, max_digits=5)),
                ('create', models.DateTimeField(null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='t2e.Order')),
                ('orderUser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='t2e.EatUser')),
            ],
        ),
        migrations.AddField(
            model_name='smallorder',
            name='UserOrder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='t2e.UserOrder'),
        ),
        migrations.AddField(
            model_name='smallorder',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='t2e.Dish'),
        ),
        migrations.AddField(
            model_name='resprof',
            name='ResType',
            field=models.ManyToManyField(to='t2e.Type'),
        ),
        migrations.AddField(
            model_name='resfavordish',
            name='Res',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='t2e.ResProf'),
        ),
        migrations.AddField(
            model_name='resfavordish',
            name='dish',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='t2e.Dish'),
        ),
        migrations.AddField(
            model_name='phone',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='t2e.ResProf'),
        ),
        migrations.AddField(
            model_name='order',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='t2e.ResProf'),
        ),
        migrations.AddField(
            model_name='menu',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='t2e.ResProf'),
        ),
        migrations.AddField(
            model_name='favortype',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='t2e.Type'),
        ),
        migrations.AddField(
            model_name='eatuser',
            name='FType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='t2e.Type'),
        ),
        migrations.AddField(
            model_name='dish',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='t2e.ResProf'),
        ),
        migrations.AddField(
            model_name='date',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='t2e.ResProf'),
        ),
    ]
