# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-24 11:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('t2e', '0002_eatuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='createUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='t2e.EatUser'),
        ),
        migrations.AddField(
            model_name='order',
            name='finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resprof',
            name='breakfast',
            field=models.CharField(default='6:00-10:00', max_length=11),
        ),
        migrations.AddField(
            model_name='resprof',
            name='dinner',
            field=models.CharField(default='17:00-21:00', max_length=11),
        ),
        migrations.AddField(
            model_name='resprof',
            name='lunch',
            field=models.CharField(default='11:00-14:00', max_length=11),
        ),
    ]
